apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sprintboard.fullname" . }}-config
  labels:
    {{- include "sprintboard.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENV: {{ .Values.config.appEnv | quote }}
  BASE_URL: {{ .Values.config.baseUrl | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  DATA_DIR: {{ ternary .Values.persistence.mountPath "data" .Values.persistence.enabled | quote }}

