replicaCount: 3

image:
  repository: mariakoneva/sprintboard
  tag: "f3db88f6b4f271244af6e27fc866ce115b74a150"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: sprintboard.example.com

config:
  appEnv: production
  baseUrl: https://sprintboard.example.com
