replicaCount: 3

image:
  repository: mariakoneva/sprintboard
  tag: "dec6313b6a49b3ceed8afbbd07d5e49f28b6c04d" # pragma: allowlist secret
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: sprintboard.127.0.0.1.nip.io

config:
  appEnv: production
  baseUrl: http://sprintboard.127.0.0.1.nip.io
